apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "jakube-3b76"
    labels:
        app: "jakube-3b76"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: jakubeb953-jakube-3b76.c8b6bfbe7b4c4737b1b6.eastus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "jakube-3b76"
                servicePort: 3000