on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n jakubeb953 -g jakubeb953900f-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n jakubeb953 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n jakubeb953 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n jakubeb953 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: jakubeb953.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t jakubeb953.azurecr.io/jakube:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push jakubeb953.azurecr.io/jakube:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_jakube_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jakubeb953 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jakubeb953`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jakubeb953
        container-registry-url: jakubeb953.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: jakubedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: jakubeb953
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
          manifests/mongo-pv.yml
        images: |
          jakubeb953.azurecr.io/jakube:${{ github.sha }}
        imagepullsecrets: |
          jakubedockerauth   
